# Generated by Django 4.2.9 on 2024-05-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_buy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buy", old_name="product", new_name="product_name",
        ),
    ]
